# Generated by Django 5.0.6 on 2025-11-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('single_date', models.DateField(blank=True, null=True)),
                ('is_single_day', models.BooleanField(default=False)),
                ('is_only_today', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seccion', models.CharField(blank=True, max_length=32)),
                ('dsc_seccion', models.CharField(blank=True, max_length=128)),
                ('cod_familia', models.CharField(blank=True, max_length=32)),
                ('dsc_familia', models.CharField(blank=True, max_length=128)),
                ('nro_plu', models.CharField(blank=True, max_length=64)),
                ('nom_plu', models.CharField(blank=True, max_length=255)),
                ('uni', models.CharField(blank=True, max_length=16)),
                ('peso', models.FloatField(default=0.0)),
                ('imp', models.FloatField(default=0.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='statsapp.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['dsc_seccion'], name='statsapp_re_dsc_sec_e46d5f_idx'), models.Index(fields=['nom_plu'], name='statsapp_re_nom_plu_b901b5_idx')],
            },
        ),
    ]
