# Generated by Django 5.0.6 on 2025-11-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='units',
            field=models.FloatField(default=0.0),
        ),
    ]
