# Generated by Django 5.0.6 on 2025-11-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0002_record_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.CharField(choices=[('santander', 'Santander'), ('bancon', 'Bancón')], max_length=32)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concept', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.FloatField(default=0.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='statsapp.bankuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='statsapp_ba_date_da9e42_idx'), models.Index(fields=['concept'], name='statsapp_ba_concept_88694f_idx'), models.Index(fields=['batch', 'date'], name='statsapp_ba_batch_i_3399f1_idx')],
            },
        ),
    ]
