# Generated by Django 5.0.6 on 2025-11-13 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0003_bankuploadbatch_banktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('partial', 'Parcial'), ('overdue', 'Vencido'), ('paid', 'Pagado')], default='active', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='statsapp_ac_last_na_7d4e83_idx'), models.Index(fields=['status'], name='statsapp_ac_status_5d0165_idx'), models.Index(fields=['-total_debt'], name='statsapp_ac_total_d_ff7d0b_idx')],
            },
        ),
    ]
