# Generated by Django 5.0.6 on 2025-11-13 15:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0004_accountclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('parcial', 'Parcial'), ('vencido', 'Vencido'), ('pagado', 'Pagado')], default='activo', max_length=16)),
                ('payments', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='statsapp.accountclient')),
            ],
            options={
                'indexes': [models.Index(fields=['client', '-date'], name='statsapp_ac_client__10961d_idx'), models.Index(fields=['status'], name='statsapp_ac_status_1b9315_idx')],
            },
        ),
    ]
