# Generated by Django 5.0.6 on 2025-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0005_accounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclient',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
