# Generated by Django 5.0.6 on 2025-11-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0007_salesmanualentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesmanualentry',
            new_name='statsapp_sa_batch_i_8704e0_idx',
            old_name='statsapp_sa_batch__2f61cb_idx',
        ),
    ]
