# Generated by Django 5.0.6 on 2026-04-21 00:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statsapp", "0010_expenses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountClientAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=120)),
                ("normalized_alias", models.CharField(max_length=120, unique=True)),
                ("auto_detected", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="ValeImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote_id", models.CharField(max_length=32, unique=True)),
                ("date", models.DateField()),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "source_photo",
                    models.FileField(blank=True, null=True, upload_to="vales/"),
                ),
                ("source_filenames", models.JSONField(blank=True, default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValeImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("client_raw", models.CharField(max_length=120)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("pending_review", models.BooleanField(default=False)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=5
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RenameIndex(
            model_name="bankexpenseassignment",
            new_name="statsapp_ba_externa_41bdba_idx",
            old_name="bankexpense_external_id_idx",
        ),
        migrations.RenameIndex(
            model_name="expenseentry",
            new_name="statsapp_ex_date_c451e0_idx",
            old_name="expenseentry_date_idx",
        ),
        migrations.RenameIndex(
            model_name="expenseentry",
            new_name="statsapp_ex_categor_2c35f3_idx",
            old_name="expenseentry_category_idx",
        ),
        migrations.RenameIndex(
            model_name="expenseentry",
            new_name="statsapp_ex_subcate_b4f78e_idx",
            old_name="expenseentry_subcategory_idx",
        ),
        migrations.RenameIndex(
            model_name="expensesubcategory",
            new_name="statsapp_ex_categor_3dc673_idx",
            old_name="expense_subcat_cat_name_idx",
        ),
        migrations.AddField(
            model_name="accountclientalias",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="statsapp.accountclient",
            ),
        ),
        migrations.AddField(
            model_name="valeimportbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vale_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="valeimportitem",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="statsapp.valeimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="valeimportitem",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vale_items",
                to="statsapp.accountclient",
            ),
        ),
        migrations.AddField(
            model_name="valeimportitem",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vale_items",
                to="statsapp.accounttransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="accountclientalias",
            index=models.Index(
                fields=["normalized_alias"], name="statsapp_ac_normali_1d7639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountclientalias",
            index=models.Index(
                fields=["client", "alias"], name="statsapp_ac_client__94f88a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valeimportbatch",
            index=models.Index(fields=["date"], name="statsapp_va_date_c82af0_idx"),
        ),
        migrations.AddIndex(
            model_name="valeimportbatch",
            index=models.Index(
                fields=["-created_at"], name="statsapp_va_created_012785_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valeimportitem",
            index=models.Index(
                fields=["batch", "date"], name="statsapp_va_batch_i_3b3787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valeimportitem",
            index=models.Index(
                fields=["client", "date"], name="statsapp_va_client__cc9590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valeimportitem",
            index=models.Index(
                fields=["pending_review"], name="statsapp_va_pending_46ca6d_idx"
            ),
        ),
    ]
