# Generated by Django 5.0.6 on 2026-07-10 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0012_recalculate_account_client_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processed', 'Procesado'), ('duplicate', 'Duplicado'), ('error', 'Error')], default='received', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='statsapp_ex_provide_9401be_idx'), models.Index(fields=['status', 'created_at'], name='statsapp_ex_status_adf336_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('account', 'Cuenta corriente'), ('getnet', 'Getnet'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('authorized', 'Autorizada'), ('rejected', 'Rechazada'), ('error', 'Error'), ('cancelled', 'Anulada')], default='draft', max_length=16)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('point_of_sale', models.PositiveIntegerField(default=0)),
                ('voucher_type', models.PositiveIntegerField(default=0)),
                ('voucher_number', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='PES', max_length=8)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('exempt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cae', models.CharField(blank=True, max_length=32)),
                ('cae_due_date', models.DateField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('provider_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='statsapp.accountclient')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='statsapp.invoice')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_link', to='statsapp.accounttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('account_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='statsapp.accounttransaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='statsapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('getnet', 'Getnet'), ('santander', 'Santander'), ('bancon', 'Bancor'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('manual', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('reconciled', 'Conciliado'), ('needs_review', 'Revisar')], default='pending', max_length=16)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='statsapp.banktransaction')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='statsapp.accountclient')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='statsapp.invoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='statsapp_in_status_0e1660_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['source', 'issue_date'], name='statsapp_in_source_e646cb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', '-issue_date'], name='statsapp_in_client__2ae622_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['external_reference'], name='statsapp_in_externa_deeb66_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_number__isnull', False)), fields=('point_of_sale', 'voucher_type', 'voucher_number'), name='unique_invoice_voucher_number'),
        ),
        migrations.AddIndex(
            model_name='invoiceaccounttransaction',
            index=models.Index(fields=['invoice'], name='statsapp_in_invoice_a82522_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaccounttransaction',
            index=models.Index(fields=['transaction'], name='statsapp_in_transac_7d0cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='statsapp_in_invoice_0f9e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['account_transaction'], name='statsapp_in_account_dd16aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['source', 'status', 'date'], name='statsapp_pa_source_2c697d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='statsapp_pa_externa_110177_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', '-date'], name='statsapp_pa_client__45e577_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='statsapp_pa_invoice_1b03db_idx'),
        ),
    ]
