# Generated by Django 5.0.6 on 2026-07-13 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0013_externalevent_invoice_invoiceaccounttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='statsapp.accountclient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='statsapp.employee')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('cash_expense', 'Efectivo por gastos'), ('account_current', 'Cuenta corriente')], max_length=24)),
                ('status', models.CharField(choices=[('auto', 'Automatico'), ('review', 'Revisar'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('matched_alias', models.CharField(blank=True, max_length=160)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_movement', to='statsapp.accounttransaction')),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_movement', to='statsapp.banktransaction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='statsapp.employee')),
                ('expense_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_movement', to='statsapp.expenseentry')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active', 'name'], name='statsapp_em_active_84a9be_idx'),
        ),
        migrations.AddIndex(
            model_name='employeealias',
            index=models.Index(fields=['normalized_alias'], name='statsapp_em_normali_9523fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeealias',
            index=models.Index(fields=['employee', 'alias'], name='statsapp_em_employe_29c123_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemovement',
            index=models.Index(fields=['employee', '-date'], name='statsapp_em_employe_03330b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemovement',
            index=models.Index(fields=['source', 'date'], name='statsapp_em_source_450e42_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemovement',
            index=models.Index(fields=['status'], name='statsapp_em_status_736bea_idx'),
        ),
    ]
