# Generated by Django 5.0.6 on 2026-07-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0015_branch_accounttransaction_branch_expenseentry_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='statsapp.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='GetnetTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('establishment_number', models.CharField(blank=True, max_length=32)),
                ('establishment_name', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getnet_terminals', to='statsapp.branch')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='statsapp.getnetterminal'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['terminal', '-date'], name='statsapp_pa_termina_81004a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', '-date'], name='statsapp_pa_branch__cc7ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='getnetterminal',
            index=models.Index(fields=['branch', 'active'], name='statsapp_ge_branch__59f033_idx'),
        ),
        migrations.AddIndex(
            model_name='getnetterminal',
            index=models.Index(fields=['establishment_number'], name='statsapp_ge_establi_676270_idx'),
        ),
    ]
