# Generated by Django 5.0.6 on 2026-07-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0016_payment_branch_payment_provider_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='statsapp.branch'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', '-issue_date'], name='statsapp_in_branch__ffc9f0_idx'),
        ),
    ]
