# Generated by Django 5.0.6 on 2026-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0018_seed_primary_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='document_type',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('cuil_cuit', 'CUIL/CUIT')], max_length=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('resignation', 'Renuncia'), ('dismissal', 'Despido'), ('other', 'Otro')], max_length=16),
        ),
    ]
