# Generated by Django 5.0.6 on 2026-07-20 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0019_employee_document_number_employee_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeRemuneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_employee_remunerations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='statsapp.employee')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee__name'],
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='statsapp_em_employe_a215f1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeremuneration',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_employee_remuneration_month'),
        ),
        migrations.AddConstraint(
            model_name='employeeremuneration',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='employee_remuneration_valid_month'),
        ),
        migrations.AddConstraint(
            model_name='employeeremuneration',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='employee_remuneration_nonnegative'),
        ),
    ]
