# Generated by Django 5.0.6 on 2026-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0020_employee_hire_date_employeeremuneration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='raw_details',
            field=models.TextField(blank=True),
        ),
    ]
