# Generated by Django 5.0.6 on 2026-07-20 13:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0021_banktransaction_raw_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='deduction_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='deduction_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_employee_account_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='deduction_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado')], max_length=16),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='employeemovement',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='employeemovement',
            index=models.Index(fields=['deduction_status', 'date'], name='statsapp_em_deducti_636349_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('account_discount_percent__gte', 0), ('account_discount_percent__lte', 100)), name='employee_account_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='employeemovement',
            constraint=models.CheckConstraint(check=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='employee_movement_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='employeemovement',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='employee_movement_discount_nonnegative'),
        ),
    ]
