from django.urls import path
from .views import (
    branches,
    upload_csv,
    stats,
    list_filters,
    list_batches,
    sales_daily,
    sales_manual_entry,
    product_trend,
    upload_bank_file,
    bank_stats,
    expenses,
    expense_detail,
    expense_categories,
    expense_assignments,
    expenses_import,
    upload_account_clients,
    list_account_clients,
    account_client_view,
    account_client_pay,
    account_transaction_create,
    account_clients_stats,
    account_transaction_delete,
)
from .auth_views import (
    CookieTokenObtainPairView,
    CookieTokenRefreshView,
    LogoutView,
    CurrentUserView,
)
from .vales_views import (
    health_status,
    clientes_list,
    clientes_aliases,
    clientes_alias_detail,
    clientes_sugerencias,
    ocr_procesar,
    vales_cargar,
    vales_item_resolver,
    vales_lotes,
    vales_lote_detail,
)
from .fiscal_views import (
    account_invoice_create_view,
    account_invoice_preview_view,
    billing_dashboard,
    getnet_import,
    getnet_terminal_detail,
    getnet_terminals,
    getnet_webhook,
    invoice_authorize,
    invoice_detail,
    invoices_list,
    payments_list,
)
from .salary_views import (
    employee_detail,
    employees_list,
    salary_movement_assign,
    salaries_dashboard,
)

urlpatterns = [
    path('branches/', branches, name='branches'),
    path('upload/', upload_csv, name='upload_csv'),
    path('stats/', stats, name='stats'),
    path('filters/', list_filters, name='filters'),
    path('batches/', list_batches, name='batches'),
    path('sales/daily/', sales_daily, name='sales_daily'),
    path('sales/manual/', sales_manual_entry, name='sales_manual_entry'),
    path('product-trend/', product_trend, name='product_trend'),
    path('bank/upload/', upload_bank_file, name='upload_bank_file'),
    path('bank/stats/', bank_stats, name='bank_stats'),
    path('expenses/', expenses, name='expenses'),
    path('expenses/import/', expenses_import, name='expenses_import'),
    path('expenses/categories/', expense_categories, name='expense_categories'),
    path('expenses/assignments/', expense_assignments, name='expense_assignments'),
    path('expenses/<uuid:pk>/', expense_detail, name='expense_detail'),
    path('accounts/upload/', upload_account_clients, name='accounts_upload'),
    path('accounts/clients/', list_account_clients, name='accounts_clients'),
    path('accounts/clients/stats/', account_clients_stats, name='accounts_clients_stats'),
    path('accounts/clients/<uuid:pk>/', account_client_view, name='accounts_client_detail'),
    path('accounts/clients/<uuid:pk>/pay/', account_client_pay, name='accounts_client_pay'),
    path('accounts/clients/<uuid:pk>/transactions/', account_transaction_create, name='accounts_transaction_create'),
    path('accounts/transactions/<str:external_id>/', account_transaction_delete, name='accounts_transaction_delete'),
    path('auth/login/', CookieTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/refresh/', CookieTokenRefreshView.as_view(), name='token_refresh'),
    path('auth/logout/', LogoutView.as_view(), name='api_logout'),
    path('auth/me/', CurrentUserView.as_view(), name='api_me'),
    path('health/', health_status, name='health_status'),
    path('clientes/', clientes_list, name='clientes_list'),
    path('clientes/aliases/', clientes_aliases, name='clientes_aliases'),
    path('clientes/aliases/<int:pk>/', clientes_alias_detail, name='clientes_alias_detail'),
    path('clientes/sugerencias/', clientes_sugerencias, name='clientes_sugerencias'),
    path('ocr/procesar/', ocr_procesar, name='ocr_procesar'),
    path('vales/cargar/', vales_cargar, name='vales_cargar'),
    path('vales/lotes/', vales_lotes, name='vales_lotes'),
    path('vales/lotes/<str:lote_id>/', vales_lote_detail, name='vales_lote_detail'),
    path('vales/items/<int:item_id>/resolver/', vales_item_resolver, name='vales_item_resolver'),
    path('billing/summary/', billing_dashboard, name='billing_summary'),
    path('billing/invoices/', invoices_list, name='billing_invoices'),
    path('billing/invoices/<uuid:pk>/', invoice_detail, name='billing_invoice_detail'),
    path('billing/invoices/<uuid:pk>/authorize/', invoice_authorize, name='billing_invoice_authorize'),
    path('billing/accounts/<uuid:pk>/preview/', account_invoice_preview_view, name='billing_account_preview'),
    path('billing/accounts/<uuid:pk>/invoices/', account_invoice_create_view, name='billing_account_invoice_create'),
    path('billing/payments/', payments_list, name='billing_payments'),
    path('billing/getnet/import/', getnet_import, name='billing_getnet_import'),
    path('billing/getnet/terminals/', getnet_terminals, name='billing_getnet_terminals'),
    path('billing/getnet/terminals/<int:pk>/', getnet_terminal_detail, name='billing_getnet_terminal_detail'),
    path('billing/getnet/webhook/', getnet_webhook, name='billing_getnet_webhook'),
    path('salaries/summary/', salaries_dashboard, name='salaries_summary'),
    path('salaries/employees/', employees_list, name='salaries_employees'),
    path('salaries/employees/<uuid:pk>/', employee_detail, name='salaries_employee_detail'),
    path('salaries/movements/assign/', salary_movement_assign, name='salaries_movement_assign'),
]
