import { expect, test } from '@playwright/test'

test('muestra sueldos por transferencias efectivo y cuenta corriente', async ({ page }) => {
  await page.goto('login')

  await page.getByLabel('Usuario').fill('e2eadmin')
  await page.getByLabel(/Contrase/).fill('e2eadmin123')
  await page.getByRole('button', { name: 'Ingresar' }).click()

  await expect(page.getByText('Viglianco ERP')).toBeVisible()
  await page.getByRole('banner').getByRole('link', { name: 'Sueldos' }).click()

  await expect(page.getByRole('heading', { name: 'Sueldos' })).toBeVisible()
  await expect(page.getByText('Total empleados')).toBeVisible()

  const northResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/summary/') && response.url().includes('branch_id=') && response.ok())
  await page.locator('#salary-branch').click()
  await page.getByRole('option', { name: 'E2E Norte', exact: true }).click()
  await northResponse
  const employeeSummary = page.getByRole('heading', { name: 'Resumen por empleado' }).locator('..').locator('..').locator('..')
  await expect(employeeSummary.getByText('Nora Norte E2E', { exact: true })).toBeVisible()
  await expect(employeeSummary.getByText('Diego E2E', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '$ 5.000' }).first()).toBeVisible()

  const centralResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/summary/') && response.url().includes('branch_id=') && response.ok())
  await page.locator('#salary-branch').click()
  await page.getByRole('option', { name: 'E2E Central', exact: true }).click()
  await centralResponse
  await expect(page.getByRole('cell', { name: 'Diego E2E', exact: true }).first()).toBeVisible()
  const detectedMovements = page.getByRole('heading', { name: 'Movimientos detectados' }).locator('..').locator('..')
  await expect(detectedMovements.getByText('Transferencia bancaria')).toBeVisible()
  await expect(detectedMovements.getByText('Efectivo por gastos')).toBeVisible()
  await expect(page.getByText('Cuenta corriente: Retiro cuenta corriente empleado')).toBeVisible()
  await expect(page.getByRole('heading', { name: '$ 67.840' }).first()).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  const accountDeductions = page.getByRole('heading', { name: 'Cuenta corriente para descontar' }).locator('..').locator('..').locator('..')
  const accountDeductionRow = accountDeductions.getByRole('row').filter({ hasText: 'Diego E2E' })
  await expect(accountDeductionRow).toContainText('$ 9.800')
  await expect(accountDeductionRow).toContainText('$ 1.960')
  await expect(accountDeductionRow).toContainText('$ 7.840')
  await expect(accountDeductionRow.getByText('9 pendientes')).toBeVisible()
  await accountDeductionRow.getByRole('button', { name: 'Confirmar' }).click()
  const deductionDialog = page.getByRole('dialog', { name: 'Confirmar descuento de cuenta corriente' })
  await expect(deductionDialog.getByRole('heading', { name: '$ 7.840' })).toBeVisible()
  const deductionResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/account-deductions/confirm/') && response.ok())
  await deductionDialog.getByRole('button', { name: 'Confirmar descuento' }).click()
  await deductionResponse
  await expect(accountDeductionRow.getByText('Confirmado')).toBeVisible()
  const aguinaldo = page.getByRole('heading', { name: 'Aguinaldo estimado' }).locator('..').locator('..').locator('..').locator('..')
  await expect(aguinaldo.getByRole('heading', { name: '$ 35.000' })).toBeVisible()
  await expect(aguinaldo.getByRole('heading', { name: 'Julio' })).toBeVisible()
  await expect(aguinaldo.getByText('1 de 6 remuneraciones confirmadas. Los meses restantes usan importes detectados.')).toBeVisible()
  await aguinaldo.getByLabel('Remuneracion computable Julio').fill('72000')
  const sacSaveResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/aguinaldo/') && response.request().method() === 'PUT' && response.ok())
  await aguinaldo.getByRole('button', { name: 'Guardar remuneraciones' }).click()
  await sacSaveResponse
  await expect(aguinaldo.getByRole('heading', { name: '$ 36.000' })).toBeVisible()
  await expect(detectedMovements.getByText('11 de 11 movimientos')).toBeVisible()
  await expect(detectedMovements.getByText('1-10 de 11')).toBeVisible()
  await detectedMovements.getByRole('button', { name: 'Go to next page' }).click()
  await expect(detectedMovements.getByText('11-11 de 11')).toBeVisible()
  await detectedMovements.getByRole('button', { name: 'Go to previous page' }).click()

  await detectedMovements.getByLabel('Origen').click()
  await page.getByRole('option', { name: 'Cuenta corriente', exact: true }).click()
  await expect(detectedMovements.getByText('9 de 11 movimientos')).toBeVisible()
  await expect(detectedMovements.getByText('Transferencia bancaria')).toHaveCount(0)

  await detectedMovements.getByLabel('Origen').click()
  await page.getByRole('option', { name: 'Todos', exact: true }).click()
  await detectedMovements.getByLabel('Buscar movimiento').fill('Pago sueldo')
  await expect(detectedMovements.getByText('1 de 11 movimientos')).toBeVisible()
  await expect(detectedMovements.getByText('Transferencia bancaria')).toBeVisible()
  await detectedMovements.getByLabel('Buscar movimiento').fill('movimiento inexistente')
  await expect(detectedMovements.getByText('Sin resultados')).toBeVisible()
  await detectedMovements.getByRole('button', { name: 'Limpiar filtros' }).click()
  await expect(detectedMovements.getByText('11 de 11 movimientos')).toBeVisible()

  const monthlyResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/monthly/') && response.ok())
  await page.getByRole('button', { name: 'Mensual' }).click()
  await monthlyResponse
  await expect(page.getByText('Acumulado y evolucion de 2026')).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await expect(employeeSummary.getByRole('button', { name: 'Diego E2E' })).toBeVisible()
  await expect(page.getByText(/JUAN CATEGORIA E2E/)).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Pendientes de identificar' })).toHaveCount(0)

  const employeeManagement = page.getByRole('heading', { name: 'Gestion de empleados' }).locator('..').locator('..').locator('..')
  const diegoRow = employeeManagement.getByRole('row').filter({ hasText: 'Diego E2E' })
  await expect(diegoRow.getByText('E2E, Diego')).toBeVisible()
  await diegoRow.getByRole('button', { name: 'Editar Diego E2E' }).click()
  const editDialog = page.getByRole('dialog', { name: 'Editar empleado' })
  await expect(editDialog.getByLabel('Sucursal')).toHaveText(/E2E Central/)
  await expect(editDialog.getByLabel('Fecha de ingreso')).toHaveValue('2026-07-01')
  await expect(editDialog.getByLabel('Descuento cuenta corriente (%)')).toHaveValue('20')
  await editDialog.getByLabel('Tipo de documento').click()
  await page.getByRole('option', { name: 'DNI', exact: true }).click()
  await editDialog.getByRole('textbox', { name: 'DNI' }).fill('19.440.880')
  await editDialog.getByRole('button', { name: 'Guardar' }).click()
  await expect(employeeManagement.getByText('DNI: 19440880')).toBeVisible()

  await employeeManagement.getByRole('button', { name: 'Dar de baja a Diego E2E' }).click()
  const terminationDialog = page.getByRole('dialog', { name: 'Dar de baja al empleado' })
  const terminationDate = terminationDialog.getByLabel('Fecha de baja')
  await expect(terminationDate).toHaveCSS('color-scheme', 'dark')
  await terminationDialog.getByLabel('Motivo').click()
  await page.getByRole('option', { name: 'Renuncia' }).click()
  await terminationDialog.getByRole('button', { name: 'Confirmar baja' }).click()
  await expect(employeeSummary.getByRole('button', { name: 'Diego E2E' })).toHaveCount(0)
  await employeeManagement.getByRole('button', { name: 'Bajas' }).click()
  await expect(employeeManagement.getByRole('row').filter({ hasText: 'Diego E2E' }).getByText('Renuncia')).toBeVisible()
  await employeeManagement.getByRole('button', { name: 'Reactivar a Diego E2E' }).click()
  await page.getByRole('dialog', { name: 'Reactivar empleado' }).getByRole('button', { name: 'Reactivar' }).click()
  await expect(employeeSummary.getByRole('button', { name: 'Diego E2E' })).toBeVisible()
  await employeeManagement.getByRole('button', { name: 'Activos' }).click()
  await expect(employeeManagement.getByRole('row').filter({ hasText: 'Diego E2E' }).getByText('Activo')).toBeVisible()
  const sectionHeadings = await page.getByRole('heading').allTextContents()
  expect(sectionHeadings.indexOf('Aguinaldo estimado')).toBeGreaterThan(sectionHeadings.indexOf('Gestion de empleados'))
})

test('mantiene utilizable sueldos en pantalla movil', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('login')
  await page.getByLabel('Usuario').fill('e2eadmin')
  await page.getByLabel(/Contrase/).fill('e2eadmin123')
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await page.goto('/ERP-Final/#/sueldos')

  await expect(page.getByRole('heading', { name: 'Sueldos' })).toBeVisible()
  await expect(page.getByText('Total empleados')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Aguinaldo estimado' })).toBeVisible()
  await expect(page.getByLabel('Remuneracion computable Julio')).toBeVisible()
  await expect(page.getByText('Alta de empleado')).toBeVisible()
  await expect(page.getByText('Gestion de empleados')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pendientes de identificar' })).toHaveCount(0)
  const rootTheme = await page.evaluate(() => {
    const styles = getComputedStyle(document.documentElement)
    return { colorScheme: styles.colorScheme, scrollbarColor: styles.scrollbarColor }
  })
  expect(rootTheme.colorScheme).toBe('dark')
  expect(rootTheme.scrollbarColor).not.toBe('auto')
  const viewportHasNoOverflow = await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)
  expect(viewportHasNoOverflow).toBe(true)
})

test('iguala las tarjetas y muestra estados vacios claros', async ({ page }) => {
  await page.goto('login')
  await page.getByLabel('Usuario').fill('e2eadmin')
  await page.getByLabel(/Contrase/).fill('e2eadmin123')
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await page.getByRole('banner').getByRole('link', { name: 'Sueldos' }).click()

  const emptySummaryResponse = page.waitForResponse((response) => response.url().includes('/api/salaries/summary/') && response.url().includes('month=6') && response.ok())
  await page.locator('#salary-month').click()
  await page.getByRole('option', { name: 'Junio', exact: true }).click()
  await emptySummaryResponse

  await expect(page.getByTestId('employee-summary-empty').getByText('Sin actividad en junio')).toBeVisible()
  await expect(page.getByTestId('movements-empty').getByText('Sin movimientos en junio')).toBeVisible()

  const summaryBox = await page.getByTestId('employee-summary-card').boundingBox()
  const movementsBox = await page.getByTestId('movements-card').boundingBox()
  expect(summaryBox).not.toBeNull()
  expect(movementsBox).not.toBeNull()
  expect(Math.abs(summaryBox.height - movementsBox.height)).toBeLessThanOrEqual(1)
})
